#!/bin/bash

# https://wiki.alice.universiteitleiden.nl/index.php?title=Running_jobs_on_ALICE
#SBATCH -p testing # gpu-short
# #SBATCH --gres=gpu:1
#SBATCH -t 1:00:00 # maximum 5 days on cartesius
#SBATCH -o /home/uraiae/jobs/slurm-%A_%a.out
#SBATCH -e /home/uraiae/jobs/slurm-%A_%a.err
#SBATCH --mail-user=a.e.urai@fsw.leidenuniv.nl # mail when done
#SBATCH --mail-type=END,FAIL # mail when done

# load necessary modules
module load Miniconda3/4.9.2
source activate hddmnn_env  # for all installed packages
# conda list 

# do something
echo "starting python job"
python generate_data.py --gres=gpu:<number>

# fit with lavaan
# module load R/4.0.5-foss-2020b
# Rscript fit_lavaan.R