#!/bin/bash

# https://servicedesk.surfsara.nl/wiki/display/WIKI/SLURM+batch+system 
#SBATCH -p shared #
#SBATCH -c 1
#SBATCH -t 2:00:00 # maximum 5 days on cartesius
#SBATCH -o /home/aeurai/jobs/slurm-%A_%a.out
#SBATCH -e /home/aeurai/jobs/slurm-%A_%a.err
#SBATCH --mail-user=a.e.urai@fsw.leidenuniv.nl # mail when done
#SBATCH --mail-type=END,FAIL # mail when done

# load necessary modules
module load 2020 # necessary for GCC 9.3.0
module load Anaconda3/2020.02
source activate hddmnn_env  # for all installed packages
# conda list 

# # do something
# echo "starting python job"
# python generate_data.py

# fit with lavaan
module load R/4.0.2-foss-2020a 
Rscript fit_lavaan.R